# Generated by Django 3.2.6 on 2021-08-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=160)),
                ('date_type', models.DateField(auto_now_add=True)),
                ('laptope_serial', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NewLaptope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_type', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to='images')),
                ('city', models.CharField(max_length=150)),
                ('product_description', models.TextField()),
                ('laptope_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixinsapp.laptopdetailes')),
            ],
        ),
    ]
